on: [push, pull_request]

name: Actions CI

jobs:
  build_and_test:
    name: yup-oauth2
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: ["service_account,hyper-rustls", "service_account", "hyper-rustls"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - run: cargo test --no-default-features --features ${{ matrix.features }}

  doc:
    name: yup-oauth2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          default: true
      - run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: --cfg yup_oauth2_docsrs

  fmt:
    name: yup-oauth2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - run: cargo fmt -- --check
